spring:
  application:
    name: eureka-server

  zipkin:
    base-url: http://localhost:9411   # URL of Zipkin server for distributed tracing

server:
  port: 8761   # Port where Eureka Server will run

eureka:
  client:
    fetch-registry: false        # Do NOT fetch registry (because this IS the registry)
    register-with-eureka: false  # Server does not self-register